blank_issues_enabled: false
contact_links:
  - name: Legacy Roleplay Nepal RedM Issue Tracker
    url: https://github.com/Legacy-Roleplay-Nepal-RedM/legacyrpnepalredm-issues-tracker/issues
    about: If your Issue/Suggestion relates to assets (Such as clothing, cars, etc), please raise it here.
  - name: Legacy Roleplay Nepal RedM
    url: https://discord.gg/VyVuaEvkcQ
    about: Join us on discord to discuss issues, ideas, etc.  
  - name: Script/Asset Explanation
    url: hhttps://github.com/Legacy-Roleplay-Nepal-RedM/legacyrpnepalredm-issues-tracker/issuesblob/main/README.md#whats-the-difference-between-script-and-asset-issues
    about: Unsure if your issue is script or asset related? Read this explanation.
